# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoQo < Formula
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.3/go-qo_0.1.3_darwin_amd64.tar.gz"
      sha256 "3b541e4da752b076b0addb603938d94c9e65fb87c92b2824db243b5bd7b93a51"

      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.3/go-qo_0.1.3_darwin_arm64.tar.gz"
      sha256 "92df78b9d31e7225e1b8ba4ce5f2cc7c5ad521d25fe30d501d10c3a285e8b808"

      def install
        bin.install "qo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.3/go-qo_0.1.3_linux_amd64.tar.gz"
      sha256 "10b1c941b7d998eb8f2bc7efff043c83f28a832eb729af9ec6fae04a60baff1d"
      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.3/go-qo_0.1.3_linux_arm64.tar.gz"
      sha256 "9177bd27390a290acfa6e0acbb0a4aae3e45bcd4947418189eed875872b24649"
      def install
        bin.install "qo"
      end
    end
  end
end
