# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-qo" do
  name "go-qo"
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-qo"

  on_macos do
    on_intel do
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/go-qo_#{version}_darwin_amd64.tar.gz"
      sha256 "92574104dcb9a854fb5feb1796d5bc65fa4a1e8cb04b781003ccd6d7fb2fd8e9"
    end
    on_arm do
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/go-qo_#{version}_darwin_arm64.tar.gz"
      sha256 "b0c4280f21d0d8f36cbadeaac0a6796cd3ef0580256686a1d7876c6b21b62887"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/go-qo_#{version}_linux_amd64.tar.gz"
      sha256 "0cb4e6fe0ffea104b53e5f7c20022d2dd2b09c1d4a4fb84dece6b0590384f1a1"
    end
    on_arm do
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/go-qo_#{version}_linux_arm64.tar.gz"
      sha256 "c7a9fcdf70894d36ac43f5ad24ecb2ee325595c419de01a81c6e8e70c466cc88"
    end
  end

  # No zap stanza required
end
