# This file was generated by GoReleaser. DO NOT EDIT.
cask "qo" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "08736125cc6f63a6d67ac81992de92c5b81af00aeef13bba0c8697dd5de9b8c5"
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/qo_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "43c274f2e41f6a64daad6b5490fbf4a18b35092fd8441f7f27614377683aab2d"
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/qo_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "66a501dba9e08d61060e487d85fab8fbedd71b14dd18d0601483960e13f95286"
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/qo_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9de7754d87a62340bcd2ca25f772205819b0a4387ba64fd5af7cea00f98d8c6e"
      url "https://github.com/kiki-ki/go-qo/releases/download/v#{version}/qo_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qo"
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qo"]
    end
  end

  # No zap stanza required
end
