# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoQo < Formula
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.5/go-qo_0.1.5_darwin_amd64.tar.gz"
      sha256 "9839fb742d1896dd0a84a4e6b3d9ad69c7ab9f2ccf772f16362bf7306c7b2805"

      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.5/go-qo_0.1.5_darwin_arm64.tar.gz"
      sha256 "3f64c98f49a3fa08f832c34f84f319f98909be12e0ae46beac5017a59d726944"

      def install
        bin.install "qo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.5/go-qo_0.1.5_linux_amd64.tar.gz"
      sha256 "61238d99165b3dcd4e6e71a1f0bdba886e676329db2a1dcdf6cefda91b11fa49"
      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.5/go-qo_0.1.5_linux_arm64.tar.gz"
      sha256 "c62295091d2e7608885236991f7e207d98c7a80b41ebc3da65a8b6201d86a4d2"
      def install
        bin.install "qo"
      end
    end
  end
end
