# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoQo < Formula
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.4/go-qo_0.1.4_darwin_amd64.tar.gz"
      sha256 "b20101c18827c788a35f42c4f5e7c7c005b6df94156230965c3a24c643cb4e7d"

      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.4/go-qo_0.1.4_darwin_arm64.tar.gz"
      sha256 "ed8ceb22d4b1280cf50047b1dd73f2a415e1351665eae6a0cf9f34d924325809"

      def install
        bin.install "qo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.4/go-qo_0.1.4_linux_amd64.tar.gz"
      sha256 "828d12c46f81924aabe8fd93257782512a041bd6bbcb814574e8862c837d94e2"
      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.4/go-qo_0.1.4_linux_arm64.tar.gz"
      sha256 "62cf011ed11c0b9e370f45ae4c713eb6a63d850722b8c7ccb6a6700befb9522a"
      def install
        bin.install "qo"
      end
    end
  end
end
