# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qo < Formula
  desc "Query JSON data with SQL"
  homepage "https://github.com/kiki-ki/go-qo"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.6/qo_0.1.6_darwin_amd64.tar.gz"
      sha256 "99674591d2546acd90576fac03cf9573d7290a68e5075c98b429338afbba85ab"

      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.6/qo_0.1.6_darwin_arm64.tar.gz"
      sha256 "1db4a4435476bf8085ff19a2bd87e158774243417bd527926dd89dd37363767a"

      def install
        bin.install "qo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.6/qo_0.1.6_linux_amd64.tar.gz"
      sha256 "7ff9cdc12a78dbf4ce4b3be64ccce7b8899469278c73d2dad6131488d3d6de42"
      def install
        bin.install "qo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiki-ki/go-qo/releases/download/v0.1.6/qo_0.1.6_linux_arm64.tar.gz"
      sha256 "6e88cedfc346da01c82311d0bb3a937ff5a5db1e42dec878983c4040f1526547"
      def install
        bin.install "qo"
      end
    end
  end
end
